/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    Background: typeof import('./components/Background.vue')['default']
    Contact: typeof import('./components/Contact.vue')['default']
    Experience: typeof import('./components/Experience.vue')['default']
    Home: typeof import('./components/Home.vue')['default']
    NavBar: typeof import('./components/NavBar.vue')['default']
    Projects: typeof import('./components/Projects.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
